# Generated by Django 5.1.15 on 2026-02-26 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('planner', '0003_replace_shopping_days_json'),
        ('recipes', '0005_tag_recipe_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='mealplan',
            name='excluded_tags',
            field=models.ManyToManyField(blank=True, related_name='+', to='recipes.tag'),
        ),
    ]
