"""
Django settings for cookless project.

Generated by 'django-admin startproject' using Django 5.1.

For more information on this file, see
https://docs.djangoproject.com/en/5.1/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.1/ref/settings/

Environment variables are loaded from .env file using django-environ.
"""

import secrets
from pathlib import Path

import environ

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Initialize django-environ with defaults
env = environ.Env(
    # Security
    DEBUG=(bool, True),
    SECRET_KEY=(str, None),
    # Network
    ALLOWED_HOSTS=(str, "localhost,127.0.0.1"),
    # Database
    DATABASE_URL=(str, ""),
    # CORS
    CORS_ALLOWED_ORIGINS=(str, "http://localhost:3000,http://localhost:5173"),
    # Email
    EMAIL_HOST=(str, ""),
    EMAIL_PORT=(int, 587),
    EMAIL_USE_TLS=(bool, True),
    EMAIL_USE_SSL=(bool, False),
    EMAIL_HOST_USER=(str, ""),
    EMAIL_HOST_PASSWORD=(str, ""),
    DEFAULT_FROM_EMAIL=(str, "noreply@localhost"),
    SERVER_EMAIL=(str, "server@localhost"),
    ADMIN_EMAIL=(str, ""),
)

# Read environment file (.env) if it exists
env_file = BASE_DIR.parent / ".env"
if env_file.exists():
    environ.Env.read_env(str(env_file), overwrite=True)


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.1/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = env("SECRET_KEY")
if not SECRET_KEY:
    if not env("DEBUG"):
        raise RuntimeError("SECRET_KEY must be set in production (DEBUG=False)")
    SECRET_KEY = secrets.token_hex(50)

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = env("DEBUG")

ALLOWED_HOSTS = [host.strip() for host in env("ALLOWED_HOSTS").split(",")]

# CSRF Trusted Origins
if DEBUG:
    CSRF_TRUSTED_ORIGINS = [
        f"http://{host.strip()}"
        for host in env("ALLOWED_HOSTS").split(",")
        if host.strip() not in ("*", "")
    ] + [origin.strip() for origin in env("CORS_ALLOWED_ORIGINS").split(",") if origin.strip()]
else:
    CSRF_TRUSTED_ORIGINS = [
        f"https://{host.strip()}"
        for host in env("ALLOWED_HOSTS").split(",")
        if host.strip() not in ("*", "")
    ]

# Support for proxies
SECURE_PROXY_SSL_HEADER = ("HTTP_X_FORWARDED_PROTO", "https")
USE_X_FORWARDED_HOST = True
USE_X_FORWARDED_PORT = True

# Secure cookies in production
if not DEBUG:
    CSRF_COOKIE_SECURE = True
    SESSION_COOKIE_SECURE = True
    SECURE_SSL_REDIRECT = env.bool("SECURE_SSL_REDIRECT", default=False)
    SECURE_REDIRECT_EXEMPT = [r"^health/$"]
    SECURE_HSTS_SECONDS = 31536000  # 1 year
    SECURE_HSTS_INCLUDE_SUBDOMAINS = True
    SECURE_HSTS_PRELOAD = True


# Application definition

INSTALLED_APPS = [
    "django.contrib.admin",
    "django.contrib.auth",
    "django.contrib.contenttypes",
    "django.contrib.sessions",
    "django.contrib.messages",
    "django.contrib.staticfiles",
    # First-party
    "users",
    "recipes",
    "planner",
    "shopping",
    # Third-party
    "corsheaders",
]

AUTH_USER_MODEL = "users.User"

MIDDLEWARE = [
    "django.middleware.security.SecurityMiddleware",
    "whitenoise.middleware.WhiteNoiseMiddleware",
    "django.contrib.sessions.middleware.SessionMiddleware",
    "corsheaders.middleware.CorsMiddleware",
    "django.middleware.common.CommonMiddleware",
    "django.middleware.csrf.CsrfViewMiddleware",
    "django.contrib.auth.middleware.AuthenticationMiddleware",
    "django.contrib.messages.middleware.MessageMiddleware",
    "django.middleware.clickjacking.XFrameOptionsMiddleware",
]

ROOT_URLCONF = "cookless.urls"

# Frontend build directory (React via Vite)
FRONTEND_DIST = BASE_DIR / "frontend_dist"

TEMPLATES = [
    {
        "BACKEND": "django.template.backends.django.DjangoTemplates",
        "DIRS": [FRONTEND_DIST] if FRONTEND_DIST.is_dir() else [],
        "APP_DIRS": True,
        "OPTIONS": {
            "context_processors": [
                "django.template.context_processors.request",
                "django.contrib.auth.context_processors.auth",
                "django.contrib.messages.context_processors.messages",
            ],
        },
    },
]

WSGI_APPLICATION = "cookless.wsgi.application"


# Database
# https://docs.djangoproject.com/en/5.1/ref/settings/#databases

database_url = env("DATABASE_URL")
if database_url:
    DATABASES = {
        "default": env.db("DATABASE_URL"),
    }
else:
    DATABASES = {
        "default": {
            "ENGINE": "django.db.backends.sqlite3",
            "NAME": BASE_DIR / "db.sqlite3",
        }
    }


# Password validation
# https://docs.djangoproject.com/en/5.1/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {"NAME": "django.contrib.auth.password_validation.UserAttributeSimilarityValidator"},
    {"NAME": "django.contrib.auth.password_validation.MinimumLengthValidator"},
    {"NAME": "django.contrib.auth.password_validation.CommonPasswordValidator"},
    {"NAME": "django.contrib.auth.password_validation.NumericPasswordValidator"},
]


# Internationalization
# https://docs.djangoproject.com/en/5.1/topics/i18n/

LANGUAGE_CODE = "en-us"

TIME_ZONE = "UTC"

USE_I18N = True

USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.1/howto/static-files/

STATIC_URL = "/static/"
STATIC_ROOT = BASE_DIR / "staticfiles"

# Media files (User uploads)
MEDIA_URL = "/media/"
MEDIA_ROOT = BASE_DIR / "media"

if FRONTEND_DIST.is_dir():
    STATICFILES_DIRS = [FRONTEND_DIST]
    WHITENOISE_ROOT = FRONTEND_DIST

# WhiteNoise configuration
STORAGES = {
    "staticfiles": {
        "BACKEND": "whitenoise.storage.CompressedManifestStaticFilesStorage",
    },
}
WHITENOISE_USE_FINDERS = DEBUG
WHITENOISE_AUTOREFRESH = DEBUG

# Default primary key field type
# https://docs.djangoproject.com/en/5.1/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = "django.db.models.BigAutoField"


# CORS Headers
# https://github.com/adamchainz/django-cors-headers

CORS_ALLOWED_ORIGINS = [
    origin.strip() for origin in env("CORS_ALLOWED_ORIGINS").split(",") if origin.strip()
]
CORS_ALLOW_CREDENTIALS = True


# WebAuthn / Passkey configuration
# Comma-separated lists to support multiple origins (e.g. localhost + LAN IP)
WEBAUTHN_RP_ID = [
    rp_id.strip()
    for rp_id in env("WEBAUTHN_RP_ID", default="localhost").split(",")
    if rp_id.strip()
]
WEBAUTHN_RP_NAME = env("WEBAUTHN_RP_NAME", default="Cook Less")
WEBAUTHN_ORIGIN = [
    origin.strip()
    for origin in env("WEBAUTHN_ORIGIN", default="http://localhost:5173").split(",")
    if origin.strip()
]


# Email Configuration
# https://docs.djangoproject.com/en/5.1/topics/email/

EMAIL_BACKEND = "django.core.mail.backends.smtp.EmailBackend"
EMAIL_HOST = env("EMAIL_HOST")
EMAIL_PORT = env("EMAIL_PORT")
EMAIL_USE_TLS = env("EMAIL_USE_TLS")
EMAIL_USE_SSL = env("EMAIL_USE_SSL")
EMAIL_HOST_USER = env("EMAIL_HOST_USER")
EMAIL_HOST_PASSWORD = env("EMAIL_HOST_PASSWORD")
DEFAULT_FROM_EMAIL = env("DEFAULT_FROM_EMAIL")
SERVER_EMAIL = env("SERVER_EMAIL")
EMAIL_TIMEOUT = 10

ADMINS = []
admin_email = env("ADMIN_EMAIL")
if admin_email:
    admin_entries = [entry.strip() for entry in admin_email.split(",")]
    for entry in admin_entries:
        if "<" in entry and ">" in entry:
            name = entry.split("<")[0].strip()
            email_addr = entry.split("<")[1].split(">")[0].strip()
            ADMINS.append((name, email_addr))
        else:
            ADMINS.append(("Admin", entry.strip()))
MANAGERS = ADMINS


# Logging Configuration
# https://docs.djangoproject.com/en/5.1/topics/logging/

LOGGING = {
    "version": 1,
    "disable_existing_loggers": False,
    "filters": {
        "require_debug_false": {
            "()": "django.utils.log.RequireDebugFalse",
        },
    },
    "formatters": {
        "simple": {
            "format": "[{levelname}] {asctime} {name} {message}",
            "style": "{",
        },
    },
    "handlers": {
        "console": {
            "level": "INFO",
            "class": "logging.StreamHandler",
            "formatter": "simple",
        },
        "mail_admins": {
            "level": "ERROR",
            "class": "django.utils.log.AdminEmailHandler",
            "filters": ["require_debug_false"],
            "include_html": True,
        },
    },
    "loggers": {
        "django": {
            "handlers": ["console"],
            "level": "INFO",
            "propagate": False,
        },
        "django.request": {
            "handlers": ["console", "mail_admins"],
            "level": "ERROR",
            "propagate": False,
        },
    },
    "root": {
        "handlers": ["console"],
        "level": "INFO",
    },
}
