# Generated by Django 5.1.15 on 2026-02-24 16:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shopping', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='shoppinglistitem',
            options={'ordering': ['ingredient__category', 'ingredient__name_en']},
        ),
    ]
