from decimal import Decimal

from django.core.management.base import BaseCommand, CommandError

from recipes.models import CookingStep, Ingredient, Recipe, RecipeIngredient, Unit
from users.models import Household

INGREDIENTS: list[dict[str, str]] = [
    # PRODUCE
    {"name_en": "onion", "name_de": "Zwiebel", "category": "PRODUCE"},
    {"name_en": "garlic", "name_de": "Knoblauch", "category": "PRODUCE"},
    {"name_en": "tomato", "name_de": "Tomate", "category": "PRODUCE"},
    {"name_en": "potato", "name_de": "Kartoffel", "category": "PRODUCE"},
    {"name_en": "carrot", "name_de": "Karotte", "category": "PRODUCE"},
    {"name_en": "bell pepper", "name_de": "Paprika", "category": "PRODUCE"},
    {"name_en": "zucchini", "name_de": "Zucchini", "category": "PRODUCE"},
    {"name_en": "broccoli", "name_de": "Brokkoli", "category": "PRODUCE"},
    {"name_en": "spinach", "name_de": "Spinat", "category": "PRODUCE"},
    {"name_en": "mushroom", "name_de": "Champignon", "category": "PRODUCE"},
    {"name_en": "lemon", "name_de": "Zitrone", "category": "PRODUCE"},
    {"name_en": "ginger", "name_de": "Ingwer", "category": "PRODUCE"},
    {"name_en": "cucumber", "name_de": "Gurke", "category": "PRODUCE"},
    {"name_en": "lettuce", "name_de": "Salat", "category": "PRODUCE"},
    {"name_en": "avocado", "name_de": "Avocado", "category": "PRODUCE"},
    {"name_en": "sweet potato", "name_de": "Süßkartoffel", "category": "PRODUCE"},
    {"name_en": "celery", "name_de": "Sellerie", "category": "PRODUCE"},
    {"name_en": "leek", "name_de": "Lauch", "category": "PRODUCE"},
    {"name_en": "cauliflower", "name_de": "Blumenkohl", "category": "PRODUCE"},
    {"name_en": "eggplant", "name_de": "Aubergine", "category": "PRODUCE"},
    {"name_en": "fresh basil", "name_de": "Frisches Basilikum", "category": "PRODUCE"},
    {"name_en": "fresh parsley", "name_de": "Frische Petersilie", "category": "PRODUCE"},
    {"name_en": "cherry tomato", "name_de": "Kirschtomate", "category": "PRODUCE"},
    {"name_en": "green beans", "name_de": "Grüne Bohnen", "category": "PRODUCE"},
    {"name_en": "corn", "name_de": "Mais", "category": "PRODUCE"},
    # DAIRY
    {"name_en": "butter", "name_de": "Butter", "category": "DAIRY"},
    {"name_en": "cream", "name_de": "Sahne", "category": "DAIRY"},
    {"name_en": "milk", "name_de": "Milch", "category": "DAIRY"},
    {"name_en": "parmesan", "name_de": "Parmesan", "category": "DAIRY"},
    {"name_en": "mozzarella", "name_de": "Mozzarella", "category": "DAIRY"},
    {"name_en": "cream cheese", "name_de": "Frischkäse", "category": "DAIRY"},
    {"name_en": "yogurt", "name_de": "Joghurt", "category": "DAIRY"},
    {"name_en": "egg", "name_de": "Ei", "category": "DAIRY"},
    {"name_en": "cheddar", "name_de": "Cheddar", "category": "DAIRY"},
    {"name_en": "feta", "name_de": "Feta", "category": "DAIRY"},
    {"name_en": "gouda", "name_de": "Gouda", "category": "DAIRY"},
    # MEAT
    {"name_en": "chicken breast", "name_de": "Hähnchenbrust", "category": "MEAT"},
    {"name_en": "ground beef", "name_de": "Rinderhackfleisch", "category": "MEAT"},
    {"name_en": "salmon fillet", "name_de": "Lachsfilet", "category": "MEAT"},
    {"name_en": "bacon", "name_de": "Speck", "category": "MEAT"},
    {"name_en": "sausage", "name_de": "Wurst", "category": "MEAT"},
    {"name_en": "pork tenderloin", "name_de": "Schweinefilet", "category": "MEAT"},
    {"name_en": "shrimp", "name_de": "Garnelen", "category": "MEAT"},
    {"name_en": "turkey breast", "name_de": "Putenbrust", "category": "MEAT"},
    {"name_en": "tuna", "name_de": "Thunfisch", "category": "MEAT"},
    # PANTRY
    {"name_en": "olive oil", "name_de": "Olivenöl", "category": "PANTRY"},
    {"name_en": "salt", "name_de": "Salz", "category": "PANTRY"},
    {"name_en": "black pepper", "name_de": "Schwarzer Pfeffer", "category": "PANTRY"},
    {"name_en": "spaghetti", "name_de": "Spaghetti", "category": "PANTRY"},
    {"name_en": "rice", "name_de": "Reis", "category": "PANTRY"},
    {"name_en": "flour", "name_de": "Mehl", "category": "PANTRY"},
    {"name_en": "sugar", "name_de": "Zucker", "category": "PANTRY"},
    {"name_en": "soy sauce", "name_de": "Sojasauce", "category": "PANTRY"},
    {"name_en": "tomato paste", "name_de": "Tomatenmark", "category": "PANTRY"},
    {"name_en": "canned tomatoes", "name_de": "Dosentomaten", "category": "PANTRY"},
    {"name_en": "vegetable broth", "name_de": "Gemüsebrühe", "category": "PANTRY"},
    {"name_en": "paprika powder", "name_de": "Paprikapulver", "category": "PANTRY"},
    {"name_en": "cumin", "name_de": "Kreuzkümmel", "category": "PANTRY"},
    {"name_en": "oregano", "name_de": "Oregano", "category": "PANTRY"},
    {"name_en": "chili flakes", "name_de": "Chiliflocken", "category": "PANTRY"},
    {"name_en": "honey", "name_de": "Honig", "category": "PANTRY"},
    {"name_en": "vinegar", "name_de": "Essig", "category": "PANTRY"},
    {"name_en": "penne", "name_de": "Penne", "category": "PANTRY"},
    {"name_en": "coconut milk", "name_de": "Kokosmilch", "category": "PANTRY"},
    {"name_en": "curry powder", "name_de": "Currypulver", "category": "PANTRY"},
    {"name_en": "mustard", "name_de": "Senf", "category": "PANTRY"},
    {"name_en": "balsamic vinegar", "name_de": "Balsamico-Essig", "category": "PANTRY"},
    {"name_en": "tortilla wraps", "name_de": "Tortilla-Wraps", "category": "PANTRY"},
    {"name_en": "peanut butter", "name_de": "Erdnussbutter", "category": "PANTRY"},
    {"name_en": "sesame oil", "name_de": "Sesamöl", "category": "PANTRY"},
    {"name_en": "bread crumbs", "name_de": "Semmelbrösel", "category": "PANTRY"},
    {"name_en": "red lentils", "name_de": "Rote Linsen", "category": "PANTRY"},
    {"name_en": "chickpeas", "name_de": "Kichererbsen", "category": "PANTRY"},
    {"name_en": "kidney beans", "name_de": "Kidneybohnen", "category": "PANTRY"},
    {"name_en": "noodles", "name_de": "Nudeln", "category": "PANTRY"},
    {"name_en": "pesto", "name_de": "Pesto", "category": "PANTRY"},
    {"name_en": "white wine", "name_de": "Weißwein", "category": "PANTRY"},
    {"name_en": "pine nuts", "name_de": "Pinienkerne", "category": "PANTRY"},
    {"name_en": "walnuts", "name_de": "Walnüsse", "category": "PANTRY"},
    # FROZEN
    {"name_en": "frozen peas", "name_de": "Tiefkühlerbsen", "category": "FROZEN"},
    {"name_en": "frozen pizza dough", "name_de": "Tiefkühl-Pizzateig", "category": "FROZEN"},
]

# Recipe data: title, list_type, servings, prep_time, cook_time, ingredients, steps
# Ingredients: (ingredient_name_en, quantity, unit_abbr)
# Steps: (method, instruction)
RECIPES: list[dict] = [
    # ── KNOWN recipes (10) ──────────────────────────────────────────────
    {
        "title": "Spaghetti Bolognese",
        "list_type": "KNOWN",
        "default_servings": 4,
        "prep_time_minutes": 15,
        "cook_time_minutes": 45,
        "ingredients": [
            ("spaghetti", Decimal("500"), "g"),
            ("ground beef", Decimal("400"), "g"),
            ("onion", Decimal("2"), "Stk"),
            ("garlic", Decimal("3"), "Stk"),
            ("canned tomatoes", Decimal("400"), "g"),
            ("tomato paste", Decimal("2"), "EL"),
            ("olive oil", Decimal("2"), "EL"),
            ("salt", Decimal("1"), "TL"),
            ("black pepper", Decimal("1"), "Prise"),
            ("oregano", Decimal("1"), "TL"),
        ],
        "steps": [
            ("MANUAL", "Dice onion and mince garlic."),
            ("MANUAL", "Heat olive oil in a large pan over medium heat."),
            ("MANUAL", "Brown the ground beef, breaking it apart with a spoon."),
            ("MANUAL", "Add onion, garlic, tomato paste, and cook for 2 minutes."),
            ("MANUAL", "Add canned tomatoes, oregano, salt, and pepper. Simmer for 30 minutes."),
            ("MACHINE", "Cook spaghetti in salted boiling water according to package directions."),
            ("MANUAL", "Serve sauce over spaghetti."),
        ],
    },
    {
        "title": "Chicken Stir-Fry",
        "list_type": "KNOWN",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 15,
        "ingredients": [
            ("chicken breast", Decimal("300"), "g"),
            ("bell pepper", Decimal("2"), "Stk"),
            ("broccoli", Decimal("200"), "g"),
            ("soy sauce", Decimal("3"), "EL"),
            ("sesame oil", Decimal("1"), "EL"),
            ("garlic", Decimal("2"), "Stk"),
            ("ginger", Decimal("1"), "TL"),
            ("rice", Decimal("200"), "g"),
        ],
        "steps": [
            ("MANUAL", "Slice chicken breast into strips, chop vegetables."),
            ("MACHINE", "Cook rice according to package directions."),
            ("MANUAL", "Heat sesame oil in a wok over high heat."),
            ("MANUAL", "Stir-fry chicken until golden, about 5 minutes."),
            ("MANUAL", "Add vegetables, garlic, ginger, and soy sauce. Cook 5 more minutes."),
            ("MANUAL", "Serve over rice."),
        ],
    },
    {
        "title": "Creamy Mushroom Pasta",
        "list_type": "KNOWN",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 20,
        "ingredients": [
            ("penne", Decimal("250"), "g"),
            ("mushroom", Decimal("300"), "g"),
            ("cream", Decimal("200"), "ml"),
            ("garlic", Decimal("2"), "Stk"),
            ("butter", Decimal("20"), "g"),
            ("parmesan", Decimal("50"), "g"),
            ("salt", Decimal("1"), "TL"),
            ("black pepper", Decimal("1"), "Prise"),
            ("fresh parsley", Decimal("1"), "EL"),
        ],
        "steps": [
            ("MANUAL", "Slice mushrooms, mince garlic."),
            ("MACHINE", "Cook penne in salted water until al dente."),
            ("MANUAL", "Melt butter in a pan, sauté mushrooms until golden."),
            ("MANUAL", "Add garlic, cook 1 minute. Pour in cream and simmer 5 minutes."),
            ("MANUAL", "Toss with drained pasta and parmesan. Season and garnish with parsley."),
        ],
    },
    {
        "title": "Salmon with Roasted Vegetables",
        "list_type": "KNOWN",
        "default_servings": 2,
        "prep_time_minutes": 15,
        "cook_time_minutes": 25,
        "ingredients": [
            ("salmon fillet", Decimal("2"), "Stk"),
            ("zucchini", Decimal("1"), "Stk"),
            ("bell pepper", Decimal("1"), "Stk"),
            ("cherry tomato", Decimal("200"), "g"),
            ("olive oil", Decimal("3"), "EL"),
            ("lemon", Decimal("1"), "Stk"),
            ("salt", Decimal("1"), "TL"),
            ("black pepper", Decimal("1"), "Prise"),
        ],
        "steps": [
            ("MANUAL", "Preheat oven to 200°C."),
            ("MANUAL", "Chop zucchini and bell pepper. Toss with olive oil, salt, pepper."),
            ("MACHINE", "Roast vegetables for 15 minutes at 200°C."),
            ("MANUAL", "Place salmon on the baking sheet, squeeze lemon over it."),
            ("MACHINE", "Bake salmon and vegetables for another 12 minutes."),
        ],
    },
    {
        "title": "Classic Potato Soup",
        "list_type": "KNOWN",
        "default_servings": 4,
        "prep_time_minutes": 15,
        "cook_time_minutes": 30,
        "ingredients": [
            ("potato", Decimal("600"), "g"),
            ("onion", Decimal("1"), "Stk"),
            ("leek", Decimal("1"), "Stk"),
            ("vegetable broth", Decimal("750"), "ml"),
            ("cream", Decimal("100"), "ml"),
            ("butter", Decimal("20"), "g"),
            ("salt", Decimal("1"), "TL"),
            ("black pepper", Decimal("1"), "Prise"),
            ("bacon", Decimal("100"), "g"),
        ],
        "steps": [
            ("MANUAL", "Peel and dice potatoes. Chop onion and leek."),
            ("MANUAL", "Melt butter in a pot, sauté onion and leek until soft."),
            ("MANUAL", "Add potatoes and broth. Bring to a boil, simmer 20 minutes."),
            ("MANUAL", "Blend until smooth, stir in cream. Season with salt and pepper."),
            ("MANUAL", "Fry bacon until crispy, use as topping."),
        ],
    },
    {
        "title": "Veggie Fried Rice",
        "list_type": "KNOWN",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 15,
        "ingredients": [
            ("rice", Decimal("250"), "g"),
            ("egg", Decimal("2"), "Stk"),
            ("carrot", Decimal("1"), "Stk"),
            ("frozen peas", Decimal("100"), "g"),
            ("soy sauce", Decimal("2"), "EL"),
            ("sesame oil", Decimal("1"), "EL"),
            ("garlic", Decimal("2"), "Stk"),
            ("corn", Decimal("100"), "g"),
        ],
        "steps": [
            ("MACHINE", "Cook rice and let it cool (or use leftover rice)."),
            ("MANUAL", "Dice carrot, mince garlic."),
            ("MANUAL", "Heat sesame oil, scramble eggs and set aside."),
            ("MANUAL", "Stir-fry carrot, peas, corn, and garlic for 3 minutes."),
            ("MANUAL", "Add rice and soy sauce, toss everything together with eggs."),
        ],
    },
    {
        "title": "Caprese Salad",
        "list_type": "KNOWN",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 0,
        "ingredients": [
            ("tomato", Decimal("3"), "Stk"),
            ("mozzarella", Decimal("250"), "g"),
            ("fresh basil", Decimal("1"), "EL"),
            ("olive oil", Decimal("2"), "EL"),
            ("balsamic vinegar", Decimal("1"), "EL"),
            ("salt", Decimal("1"), "Prise"),
            ("black pepper", Decimal("1"), "Prise"),
        ],
        "steps": [
            ("MANUAL", "Slice tomatoes and mozzarella into rounds."),
            ("MANUAL", "Arrange alternating slices on a plate."),
            ("MANUAL", "Top with basil leaves, drizzle with olive oil and balsamic vinegar."),
            ("MANUAL", "Season with salt and pepper."),
        ],
    },
    {
        "title": "Chicken Wraps",
        "list_type": "KNOWN",
        "default_servings": 2,
        "prep_time_minutes": 15,
        "cook_time_minutes": 10,
        "ingredients": [
            ("chicken breast", Decimal("300"), "g"),
            ("tortilla wraps", Decimal("4"), "Stk"),
            ("lettuce", Decimal("100"), "g"),
            ("tomato", Decimal("2"), "Stk"),
            ("yogurt", Decimal("100"), "g"),
            ("cumin", Decimal("1"), "TL"),
            ("paprika powder", Decimal("1"), "TL"),
            ("olive oil", Decimal("1"), "EL"),
            ("salt", Decimal("1"), "TL"),
        ],
        "steps": [
            ("MANUAL", "Season chicken with cumin, paprika, and salt."),
            ("MANUAL", "Heat olive oil and cook chicken until done, about 5 min per side."),
            ("MANUAL", "Slice chicken into strips."),
            ("MANUAL", "Warm tortillas, fill with lettuce, tomato, chicken, and yogurt."),
        ],
    },
    {
        "title": "Broccoli Cheddar Soup",
        "list_type": "KNOWN",
        "default_servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 25,
        "ingredients": [
            ("broccoli", Decimal("500"), "g"),
            ("cheddar", Decimal("150"), "g"),
            ("onion", Decimal("1"), "Stk"),
            ("vegetable broth", Decimal("500"), "ml"),
            ("cream", Decimal("100"), "ml"),
            ("butter", Decimal("20"), "g"),
            ("flour", Decimal("2"), "EL"),
            ("salt", Decimal("1"), "TL"),
            ("black pepper", Decimal("1"), "Prise"),
        ],
        "steps": [
            ("MANUAL", "Chop broccoli into florets, dice onion."),
            ("MANUAL", "Melt butter, sauté onion. Stir in flour and cook 1 minute."),
            ("MANUAL", "Gradually add broth, stirring constantly. Add broccoli."),
            ("MANUAL", "Simmer 15 minutes until broccoli is tender."),
            ("MANUAL", "Blend partially, stir in cream and cheddar until melted."),
        ],
    },
    {
        "title": "One-Pan Lemon Chicken",
        "list_type": "KNOWN",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 30,
        "ingredients": [
            ("chicken breast", Decimal("2"), "Stk"),
            ("potato", Decimal("400"), "g"),
            ("lemon", Decimal("1"), "Stk"),
            ("garlic", Decimal("4"), "Stk"),
            ("olive oil", Decimal("3"), "EL"),
            ("oregano", Decimal("1"), "TL"),
            ("salt", Decimal("1"), "TL"),
            ("black pepper", Decimal("1"), "Prise"),
        ],
        "steps": [
            ("MANUAL", "Preheat oven to 200°C. Cut potatoes into wedges."),
            ("MANUAL", "Toss potatoes with olive oil, garlic, oregano, salt, and pepper."),
            ("MANUAL", "Place chicken and potatoes in a baking dish, squeeze lemon over."),
            ("MACHINE", "Bake for 30 minutes until chicken is cooked through."),
        ],
    },
    # ── TO_TRY recipes (50) ─────────────────────────────────────────────
    {
        "title": "Thai Green Curry",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 15,
        "cook_time_minutes": 25,
        "ingredients": [
            ("chicken breast", Decimal("400"), "g"),
            ("coconut milk", Decimal("400"), "ml"),
            ("bell pepper", Decimal("1"), "Stk"),
            ("zucchini", Decimal("1"), "Stk"),
            ("rice", Decimal("300"), "g"),
            ("garlic", Decimal("2"), "Stk"),
            ("ginger", Decimal("1"), "TL"),
            ("soy sauce", Decimal("2"), "EL"),
        ],
        "steps": [
            ("MANUAL", "Slice chicken and vegetables."),
            ("MANUAL", "Sauté garlic and ginger, add chicken until browned."),
            ("MANUAL", "Pour in coconut milk, add vegetables and soy sauce. Simmer 20 min."),
            ("MACHINE", "Cook rice."),
        ],
    },
    {
        "title": "Eggplant Parmesan",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 20,
        "cook_time_minutes": 40,
        "ingredients": [
            ("eggplant", Decimal("2"), "Stk"),
            ("canned tomatoes", Decimal("400"), "g"),
            ("mozzarella", Decimal("200"), "g"),
            ("parmesan", Decimal("50"), "g"),
            ("bread crumbs", Decimal("100"), "g"),
            ("egg", Decimal("2"), "Stk"),
            ("olive oil", Decimal("3"), "EL"),
            ("fresh basil", Decimal("1"), "EL"),
        ],
        "steps": [
            ("MANUAL", "Slice eggplant, dip in egg then breadcrumbs."),
            ("MANUAL", "Fry until golden on both sides."),
            ("MANUAL", "Layer eggplant, tomato sauce, and cheese in a baking dish."),
            ("MACHINE", "Bake at 180°C for 25 minutes."),
        ],
    },
    {
        "title": "Shrimp Scampi",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 15,
        "ingredients": [
            ("shrimp", Decimal("300"), "g"),
            ("spaghetti", Decimal("200"), "g"),
            ("garlic", Decimal("4"), "Stk"),
            ("butter", Decimal("30"), "g"),
            ("white wine", Decimal("100"), "ml"),
            ("lemon", Decimal("1"), "Stk"),
            ("chili flakes", Decimal("1"), "Prise"),
            ("fresh parsley", Decimal("1"), "EL"),
        ],
        "steps": [
            ("MACHINE", "Cook spaghetti until al dente."),
            ("MANUAL", "Sauté garlic in butter, add shrimp and cook 2 minutes per side."),
            ("MANUAL", "Add white wine, lemon juice, and chili flakes. Simmer 3 minutes."),
            ("MANUAL", "Toss with pasta and parsley."),
        ],
    },
    {
        "title": "Cauliflower Mac and Cheese",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 25,
        "ingredients": [
            ("cauliflower", Decimal("1"), "Stk"),
            ("penne", Decimal("300"), "g"),
            ("cheddar", Decimal("200"), "g"),
            ("cream", Decimal("150"), "ml"),
            ("butter", Decimal("20"), "g"),
            ("mustard", Decimal("1"), "TL"),
            ("salt", Decimal("1"), "TL"),
        ],
        "steps": [
            ("MANUAL", "Cut cauliflower into small florets."),
            ("MACHINE", "Cook pasta and cauliflower together until tender."),
            ("MANUAL", "Make cheese sauce: melt butter, add cream, cheddar, and mustard."),
            ("MANUAL", "Combine pasta, cauliflower, and cheese sauce."),
        ],
    },
    {
        "title": "Lentil Soup",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 30,
        "ingredients": [
            ("red lentils", Decimal("250"), "g"),
            ("onion", Decimal("1"), "Stk"),
            ("carrot", Decimal("2"), "Stk"),
            ("garlic", Decimal("2"), "Stk"),
            ("vegetable broth", Decimal("750"), "ml"),
            ("cumin", Decimal("1"), "TL"),
            ("curry powder", Decimal("1"), "TL"),
            ("lemon", Decimal("1"), "Stk"),
        ],
        "steps": [
            ("MANUAL", "Dice onion and carrots, mince garlic."),
            ("MANUAL", "Sauté vegetables with cumin and curry powder."),
            ("MANUAL", "Add lentils and broth. Simmer 25 minutes."),
            ("MANUAL", "Blend until smooth, finish with lemon juice."),
        ],
    },
    {
        "title": "Pesto Chicken with Roasted Tomatoes",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 25,
        "ingredients": [
            ("chicken breast", Decimal("2"), "Stk"),
            ("pesto", Decimal("3"), "EL"),
            ("cherry tomato", Decimal("200"), "g"),
            ("mozzarella", Decimal("100"), "g"),
            ("olive oil", Decimal("1"), "EL"),
            ("salt", Decimal("1"), "Prise"),
        ],
        "steps": [
            ("MANUAL", "Spread pesto over chicken breasts."),
            ("MANUAL", "Place in baking dish with cherry tomatoes and olive oil."),
            ("MACHINE", "Bake at 200°C for 20 minutes."),
            ("MANUAL", "Add mozzarella slices, bake 5 more minutes."),
        ],
    },
    {
        "title": "Sweet Potato Curry",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 15,
        "cook_time_minutes": 30,
        "ingredients": [
            ("sweet potato", Decimal("500"), "g"),
            ("coconut milk", Decimal("400"), "ml"),
            ("chickpeas", Decimal("250"), "g"),
            ("onion", Decimal("1"), "Stk"),
            ("garlic", Decimal("2"), "Stk"),
            ("curry powder", Decimal("2"), "TL"),
            ("spinach", Decimal("100"), "g"),
            ("rice", Decimal("250"), "g"),
        ],
        "steps": [
            ("MANUAL", "Peel and cube sweet potatoes."),
            ("MANUAL", "Sauté onion and garlic, add curry powder."),
            ("MANUAL", "Add sweet potatoes, coconut milk, and chickpeas. Simmer 25 min."),
            ("MANUAL", "Stir in spinach until wilted. Serve over rice."),
        ],
    },
    {
        "title": "Mushroom Risotto",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 35,
        "ingredients": [
            ("rice", Decimal("200"), "g"),
            ("mushroom", Decimal("250"), "g"),
            ("onion", Decimal("1"), "Stk"),
            ("white wine", Decimal("100"), "ml"),
            ("vegetable broth", Decimal("500"), "ml"),
            ("parmesan", Decimal("50"), "g"),
            ("butter", Decimal("30"), "g"),
            ("olive oil", Decimal("1"), "EL"),
        ],
        "steps": [
            ("MANUAL", "Dice onion, slice mushrooms."),
            ("MANUAL", "Sauté onion in olive oil, add rice and toast 1 minute."),
            ("MANUAL", "Add white wine, stir until absorbed."),
            ("MANUAL", "Add broth one ladle at a time, stirring constantly, for 20 min."),
            ("MANUAL", "Fold in sautéed mushrooms, butter, and parmesan."),
        ],
    },
    {
        "title": "Greek Salad",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 15,
        "cook_time_minutes": 0,
        "ingredients": [
            ("cucumber", Decimal("1"), "Stk"),
            ("tomato", Decimal("3"), "Stk"),
            ("feta", Decimal("150"), "g"),
            ("onion", Decimal("1"), "Stk"),
            ("olive oil", Decimal("3"), "EL"),
            ("oregano", Decimal("1"), "TL"),
            ("salt", Decimal("1"), "Prise"),
        ],
        "steps": [
            ("MANUAL", "Chop cucumber, tomatoes, and onion into chunks."),
            ("MANUAL", "Combine in a bowl, crumble feta on top."),
            ("MANUAL", "Drizzle with olive oil, sprinkle oregano and salt."),
        ],
    },
    {
        "title": "Pork Schnitzel",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 15,
        "cook_time_minutes": 10,
        "ingredients": [
            ("pork tenderloin", Decimal("300"), "g"),
            ("flour", Decimal("50"), "g"),
            ("egg", Decimal("2"), "Stk"),
            ("bread crumbs", Decimal("100"), "g"),
            ("butter", Decimal("50"), "g"),
            ("lemon", Decimal("1"), "Stk"),
            ("salt", Decimal("1"), "TL"),
        ],
        "steps": [
            ("MANUAL", "Pound pork to 5mm thickness, season with salt."),
            ("MANUAL", "Dredge in flour, dip in egg, coat with breadcrumbs."),
            ("MANUAL", "Fry in butter over medium-high heat, 3 min per side."),
            ("MANUAL", "Serve with lemon wedge."),
        ],
    },
    {
        "title": "Avocado Toast with Egg",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 5,
        "cook_time_minutes": 5,
        "ingredients": [
            ("avocado", Decimal("2"), "Stk"),
            ("egg", Decimal("2"), "Stk"),
            ("lemon", Decimal("1"), "Stk"),
            ("chili flakes", Decimal("1"), "Prise"),
            ("salt", Decimal("1"), "Prise"),
        ],
        "steps": [
            ("MANUAL", "Toast bread slices."),
            ("MANUAL", "Mash avocado with lemon juice and salt."),
            ("MANUAL", "Fry or poach eggs."),
            ("MANUAL", "Spread avocado on toast, top with egg and chili flakes."),
        ],
    },
    {
        "title": "Tuna Pasta Salad",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 12,
        "ingredients": [
            ("penne", Decimal("300"), "g"),
            ("tuna", Decimal("200"), "g"),
            ("corn", Decimal("150"), "g"),
            ("cucumber", Decimal("1"), "Stk"),
            ("yogurt", Decimal("100"), "g"),
            ("mustard", Decimal("1"), "TL"),
            ("salt", Decimal("1"), "TL"),
        ],
        "steps": [
            ("MACHINE", "Cook penne and let cool."),
            ("MANUAL", "Dice cucumber, drain tuna and corn."),
            ("MANUAL", "Mix yogurt and mustard for dressing."),
            ("MANUAL", "Combine everything and toss with dressing."),
        ],
    },
    {
        "title": "Chickpea Buddha Bowl",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 15,
        "cook_time_minutes": 20,
        "ingredients": [
            ("chickpeas", Decimal("250"), "g"),
            ("sweet potato", Decimal("1"), "Stk"),
            ("spinach", Decimal("100"), "g"),
            ("avocado", Decimal("1"), "Stk"),
            ("rice", Decimal("150"), "g"),
            ("olive oil", Decimal("2"), "EL"),
            ("cumin", Decimal("1"), "TL"),
            ("lemon", Decimal("1"), "Stk"),
        ],
        "steps": [
            ("MANUAL", "Cube sweet potato, toss with olive oil and cumin."),
            ("MACHINE", "Roast sweet potato at 200°C for 20 minutes. Cook rice."),
            ("MANUAL", "Warm chickpeas in a pan."),
            ("MANUAL", "Assemble bowls: rice, sweet potato, chickpeas, spinach, avocado."),
            ("MANUAL", "Drizzle with lemon juice."),
        ],
    },
    {
        "title": "Beef Tacos",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 15,
        "cook_time_minutes": 15,
        "ingredients": [
            ("ground beef", Decimal("400"), "g"),
            ("tortilla wraps", Decimal("8"), "Stk"),
            ("tomato", Decimal("2"), "Stk"),
            ("lettuce", Decimal("100"), "g"),
            ("cheddar", Decimal("100"), "g"),
            ("cumin", Decimal("1"), "TL"),
            ("paprika powder", Decimal("1"), "TL"),
            ("salt", Decimal("1"), "TL"),
        ],
        "steps": [
            ("MANUAL", "Season and brown ground beef with cumin, paprika, and salt."),
            ("MANUAL", "Dice tomatoes, shred lettuce, grate cheese."),
            ("MANUAL", "Warm tortillas."),
            ("MANUAL", "Assemble tacos with beef, toppings, and cheese."),
        ],
    },
    {
        "title": "Spinach and Feta Quiche",
        "list_type": "TO_TRY",
        "default_servings": 6,
        "prep_time_minutes": 20,
        "cook_time_minutes": 35,
        "ingredients": [
            ("spinach", Decimal("200"), "g"),
            ("feta", Decimal("150"), "g"),
            ("egg", Decimal("4"), "Stk"),
            ("cream", Decimal("200"), "ml"),
            ("onion", Decimal("1"), "Stk"),
            ("butter", Decimal("20"), "g"),
            ("salt", Decimal("1"), "TL"),
            ("black pepper", Decimal("1"), "Prise"),
        ],
        "steps": [
            ("MANUAL", "Sauté onion in butter, add spinach until wilted."),
            ("MANUAL", "Whisk eggs and cream, season with salt and pepper."),
            ("MANUAL", "Spread spinach in a baking dish, crumble feta on top."),
            ("MANUAL", "Pour egg mixture over. Bake at 180°C for 35 minutes."),
        ],
    },
    {
        "title": "Honey Garlic Salmon",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 5,
        "cook_time_minutes": 15,
        "ingredients": [
            ("salmon fillet", Decimal("2"), "Stk"),
            ("honey", Decimal("2"), "EL"),
            ("soy sauce", Decimal("2"), "EL"),
            ("garlic", Decimal("3"), "Stk"),
            ("butter", Decimal("20"), "g"),
            ("rice", Decimal("200"), "g"),
        ],
        "steps": [
            ("MANUAL", "Mix honey, soy sauce, and minced garlic."),
            ("MANUAL", "Sear salmon in butter, 3 minutes per side."),
            ("MANUAL", "Pour glaze over salmon, cook 2 more minutes."),
            ("MACHINE", "Cook rice."),
        ],
    },
    {
        "title": "Zucchini Fritters",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 15,
        "cook_time_minutes": 10,
        "ingredients": [
            ("zucchini", Decimal("2"), "Stk"),
            ("egg", Decimal("1"), "Stk"),
            ("flour", Decimal("50"), "g"),
            ("feta", Decimal("50"), "g"),
            ("garlic", Decimal("1"), "Stk"),
            ("olive oil", Decimal("3"), "EL"),
            ("salt", Decimal("1"), "TL"),
        ],
        "steps": [
            ("MANUAL", "Grate zucchini, squeeze out excess moisture."),
            ("MANUAL", "Mix with egg, flour, crumbled feta, garlic, and salt."),
            ("MANUAL", "Form patties and fry in olive oil until golden, 3 min per side."),
        ],
    },
    {
        "title": "Turkey Meatballs in Tomato Sauce",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 20,
        "cook_time_minutes": 25,
        "ingredients": [
            ("turkey breast", Decimal("400"), "g"),
            ("bread crumbs", Decimal("50"), "g"),
            ("egg", Decimal("1"), "Stk"),
            ("canned tomatoes", Decimal("400"), "g"),
            ("garlic", Decimal("2"), "Stk"),
            ("oregano", Decimal("1"), "TL"),
            ("olive oil", Decimal("2"), "EL"),
            ("spaghetti", Decimal("300"), "g"),
        ],
        "steps": [
            ("MANUAL", "Mix turkey, breadcrumbs, egg, garlic, and oregano. Form balls."),
            ("MANUAL", "Brown meatballs in olive oil."),
            ("MANUAL", "Add canned tomatoes, simmer 20 minutes."),
            ("MACHINE", "Cook spaghetti."),
        ],
    },
    {
        "title": "Peanut Noodles",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 10,
        "ingredients": [
            ("noodles", Decimal("200"), "g"),
            ("peanut butter", Decimal("3"), "EL"),
            ("soy sauce", Decimal("2"), "EL"),
            ("sesame oil", Decimal("1"), "EL"),
            ("garlic", Decimal("2"), "Stk"),
            ("carrot", Decimal("1"), "Stk"),
            ("cucumber", Decimal("1"), "Stk"),
        ],
        "steps": [
            ("MACHINE", "Cook noodles."),
            ("MANUAL", "Whisk peanut butter, soy sauce, sesame oil, and minced garlic."),
            ("MANUAL", "Julienne carrot and cucumber."),
            ("MANUAL", "Toss noodles with sauce and vegetables."),
        ],
    },
    {
        "title": "Stuffed Bell Peppers",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 20,
        "cook_time_minutes": 35,
        "ingredients": [
            ("bell pepper", Decimal("4"), "Stk"),
            ("rice", Decimal("200"), "g"),
            ("ground beef", Decimal("300"), "g"),
            ("canned tomatoes", Decimal("200"), "g"),
            ("onion", Decimal("1"), "Stk"),
            ("cheddar", Decimal("100"), "g"),
            ("cumin", Decimal("1"), "TL"),
            ("salt", Decimal("1"), "TL"),
        ],
        "steps": [
            ("MANUAL", "Cut tops off peppers and remove seeds."),
            ("MACHINE", "Cook rice."),
            ("MANUAL", "Brown beef with onion and cumin, mix with rice and tomatoes."),
            ("MANUAL", "Stuff peppers, top with cheese."),
            ("MACHINE", "Bake at 180°C for 25 minutes."),
        ],
    },
    {
        "title": "Creamy Tomato Soup",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 25,
        "ingredients": [
            ("canned tomatoes", Decimal("800"), "g"),
            ("onion", Decimal("1"), "Stk"),
            ("garlic", Decimal("3"), "Stk"),
            ("cream", Decimal("100"), "ml"),
            ("vegetable broth", Decimal("250"), "ml"),
            ("butter", Decimal("20"), "g"),
            ("sugar", Decimal("1"), "TL"),
            ("fresh basil", Decimal("1"), "EL"),
        ],
        "steps": [
            ("MANUAL", "Sauté onion and garlic in butter."),
            ("MANUAL", "Add tomatoes, broth, and sugar. Simmer 20 minutes."),
            ("MANUAL", "Blend until smooth, stir in cream."),
            ("MANUAL", "Garnish with fresh basil."),
        ],
    },
    {
        "title": "Vegetable Stir-Fry with Tofu",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 15,
        "cook_time_minutes": 15,
        "ingredients": [
            ("broccoli", Decimal("200"), "g"),
            ("bell pepper", Decimal("1"), "Stk"),
            ("carrot", Decimal("1"), "Stk"),
            ("soy sauce", Decimal("3"), "EL"),
            ("sesame oil", Decimal("1"), "EL"),
            ("garlic", Decimal("2"), "Stk"),
            ("ginger", Decimal("1"), "TL"),
            ("rice", Decimal("200"), "g"),
        ],
        "steps": [
            ("MANUAL", "Chop all vegetables."),
            ("MACHINE", "Cook rice."),
            ("MANUAL", "Heat sesame oil, stir-fry vegetables with garlic and ginger."),
            ("MANUAL", "Add soy sauce, cook 2 more minutes. Serve over rice."),
        ],
    },
    {
        "title": "Bacon Carbonara",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 15,
        "ingredients": [
            ("spaghetti", Decimal("200"), "g"),
            ("bacon", Decimal("150"), "g"),
            ("egg", Decimal("3"), "Stk"),
            ("parmesan", Decimal("50"), "g"),
            ("black pepper", Decimal("1"), "TL"),
            ("garlic", Decimal("2"), "Stk"),
        ],
        "steps": [
            ("MACHINE", "Cook spaghetti until al dente."),
            ("MANUAL", "Fry bacon until crispy, add garlic."),
            ("MANUAL", "Whisk eggs with parmesan and pepper."),
            ("MANUAL", "Toss hot pasta with bacon, then egg mixture (off heat)."),
        ],
    },
    {
        "title": "Minestrone",
        "list_type": "TO_TRY",
        "default_servings": 6,
        "prep_time_minutes": 15,
        "cook_time_minutes": 30,
        "ingredients": [
            ("carrot", Decimal("2"), "Stk"),
            ("celery", Decimal("2"), "Stk"),
            ("onion", Decimal("1"), "Stk"),
            ("kidney beans", Decimal("250"), "g"),
            ("canned tomatoes", Decimal("400"), "g"),
            ("vegetable broth", Decimal("750"), "ml"),
            ("penne", Decimal("100"), "g"),
            ("olive oil", Decimal("2"), "EL"),
        ],
        "steps": [
            ("MANUAL", "Dice carrot, celery, and onion."),
            ("MANUAL", "Sauté vegetables in olive oil for 5 minutes."),
            ("MANUAL", "Add beans, tomatoes, and broth. Simmer 20 minutes."),
            ("MANUAL", "Add pasta, cook 10 more minutes."),
        ],
    },
    {
        "title": "Garlic Butter Shrimp",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 5,
        "cook_time_minutes": 10,
        "ingredients": [
            ("shrimp", Decimal("300"), "g"),
            ("butter", Decimal("40"), "g"),
            ("garlic", Decimal("4"), "Stk"),
            ("lemon", Decimal("1"), "Stk"),
            ("chili flakes", Decimal("1"), "Prise"),
            ("fresh parsley", Decimal("1"), "EL"),
        ],
        "steps": [
            ("MANUAL", "Melt butter, sauté garlic until fragrant."),
            ("MANUAL", "Add shrimp, cook 2 minutes per side."),
            ("MANUAL", "Squeeze lemon, add chili flakes and parsley."),
        ],
    },
    {
        "title": "Potato Gratin",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 15,
        "cook_time_minutes": 45,
        "ingredients": [
            ("potato", Decimal("800"), "g"),
            ("cream", Decimal("300"), "ml"),
            ("gouda", Decimal("150"), "g"),
            ("garlic", Decimal("2"), "Stk"),
            ("butter", Decimal("20"), "g"),
            ("salt", Decimal("1"), "TL"),
            ("black pepper", Decimal("1"), "Prise"),
        ],
        "steps": [
            ("MANUAL", "Peel and thinly slice potatoes."),
            ("MANUAL", "Rub baking dish with garlic and butter."),
            ("MANUAL", "Layer potatoes, season each layer, pour cream over."),
            ("MANUAL", "Top with grated gouda."),
            ("MACHINE", "Bake at 180°C for 45 minutes."),
        ],
    },
    {
        "title": "Chicken Caesar Salad",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 15,
        "cook_time_minutes": 10,
        "ingredients": [
            ("chicken breast", Decimal("2"), "Stk"),
            ("lettuce", Decimal("200"), "g"),
            ("parmesan", Decimal("50"), "g"),
            ("olive oil", Decimal("2"), "EL"),
            ("lemon", Decimal("1"), "Stk"),
            ("garlic", Decimal("1"), "Stk"),
            ("yogurt", Decimal("50"), "g"),
        ],
        "steps": [
            ("MANUAL", "Season and grill chicken, then slice."),
            ("MANUAL", "Mix yogurt, lemon juice, garlic, and parmesan for dressing."),
            ("MANUAL", "Toss lettuce with dressing, top with chicken and extra parmesan."),
        ],
    },
    {
        "title": "Baked Feta Pasta",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 30,
        "ingredients": [
            ("penne", Decimal("400"), "g"),
            ("feta", Decimal("200"), "g"),
            ("cherry tomato", Decimal("500"), "g"),
            ("garlic", Decimal("3"), "Stk"),
            ("olive oil", Decimal("3"), "EL"),
            ("chili flakes", Decimal("1"), "Prise"),
            ("fresh basil", Decimal("1"), "EL"),
        ],
        "steps": [
            ("MANUAL", "Place feta in center of baking dish, surround with tomatoes and garlic."),
            ("MANUAL", "Drizzle with olive oil and chili flakes."),
            ("MACHINE", "Bake at 200°C for 25 minutes. Cook pasta."),
            ("MANUAL", "Mash feta and tomatoes, toss with pasta and basil."),
        ],
    },
    {
        "title": "Green Bean Casserole",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 30,
        "ingredients": [
            ("green beans", Decimal("500"), "g"),
            ("mushroom", Decimal("200"), "g"),
            ("cream", Decimal("200"), "ml"),
            ("onion", Decimal("1"), "Stk"),
            ("garlic", Decimal("2"), "Stk"),
            ("butter", Decimal("20"), "g"),
            ("bread crumbs", Decimal("50"), "g"),
        ],
        "steps": [
            ("MANUAL", "Blanch green beans for 5 minutes."),
            ("MANUAL", "Sauté mushrooms, onion, and garlic in butter."),
            ("MANUAL", "Combine beans, mushroom mixture, and cream in a dish."),
            ("MANUAL", "Top with breadcrumbs."),
            ("MACHINE", "Bake at 180°C for 20 minutes."),
        ],
    },
    {
        "title": "Shakshuka",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 20,
        "ingredients": [
            ("egg", Decimal("4"), "Stk"),
            ("canned tomatoes", Decimal("400"), "g"),
            ("bell pepper", Decimal("1"), "Stk"),
            ("onion", Decimal("1"), "Stk"),
            ("garlic", Decimal("2"), "Stk"),
            ("cumin", Decimal("1"), "TL"),
            ("paprika powder", Decimal("1"), "TL"),
            ("olive oil", Decimal("2"), "EL"),
        ],
        "steps": [
            ("MANUAL", "Sauté onion, pepper, and garlic in olive oil."),
            ("MANUAL", "Add spices, then tomatoes. Simmer 10 minutes."),
            ("MANUAL", "Make wells, crack eggs into sauce."),
            ("MANUAL", "Cover and cook until eggs are set, about 8 minutes."),
        ],
    },
    {
        "title": "Walnut Pesto Pasta",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 12,
        "ingredients": [
            ("spaghetti", Decimal("200"), "g"),
            ("walnuts", Decimal("50"), "g"),
            ("fresh basil", Decimal("2"), "EL"),
            ("parmesan", Decimal("50"), "g"),
            ("garlic", Decimal("2"), "Stk"),
            ("olive oil", Decimal("4"), "EL"),
            ("salt", Decimal("1"), "Prise"),
        ],
        "steps": [
            ("MACHINE", "Cook spaghetti."),
            ("MANUAL", "Blend walnuts, basil, parmesan, garlic, and olive oil into pesto."),
            ("MANUAL", "Toss hot pasta with pesto and a splash of pasta water."),
        ],
    },
    {
        "title": "Crispy Chicken Thighs with Potatoes",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 40,
        "ingredients": [
            ("chicken breast", Decimal("4"), "Stk"),
            ("potato", Decimal("500"), "g"),
            ("garlic", Decimal("4"), "Stk"),
            ("olive oil", Decimal("3"), "EL"),
            ("paprika powder", Decimal("1"), "TL"),
            ("oregano", Decimal("1"), "TL"),
            ("salt", Decimal("1"), "TL"),
        ],
        "steps": [
            ("MANUAL", "Cut potatoes into wedges, toss with oil and spices."),
            ("MANUAL", "Season chicken with paprika, oregano, and salt."),
            ("MANUAL", "Arrange in a baking dish with garlic cloves."),
            ("MACHINE", "Bake at 200°C for 40 minutes."),
        ],
    },
    {
        "title": "Coconut Lentil Dhal",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 25,
        "ingredients": [
            ("red lentils", Decimal("250"), "g"),
            ("coconut milk", Decimal("400"), "ml"),
            ("onion", Decimal("1"), "Stk"),
            ("garlic", Decimal("3"), "Stk"),
            ("ginger", Decimal("1"), "TL"),
            ("curry powder", Decimal("2"), "TL"),
            ("tomato paste", Decimal("1"), "EL"),
            ("rice", Decimal("250"), "g"),
        ],
        "steps": [
            ("MANUAL", "Sauté onion, garlic, and ginger."),
            ("MANUAL", "Add curry powder and tomato paste, cook 1 minute."),
            ("MANUAL", "Add lentils and coconut milk. Simmer 20 minutes."),
            ("MACHINE", "Cook rice."),
        ],
    },
    {
        "title": "Caprese Chicken",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 20,
        "ingredients": [
            ("chicken breast", Decimal("2"), "Stk"),
            ("mozzarella", Decimal("100"), "g"),
            ("tomato", Decimal("2"), "Stk"),
            ("fresh basil", Decimal("1"), "EL"),
            ("balsamic vinegar", Decimal("2"), "EL"),
            ("olive oil", Decimal("1"), "EL"),
            ("salt", Decimal("1"), "Prise"),
        ],
        "steps": [
            ("MANUAL", "Season chicken and sear in olive oil until golden."),
            ("MANUAL", "Top with tomato slices and mozzarella."),
            ("MACHINE", "Bake at 180°C for 15 minutes."),
            ("MANUAL", "Drizzle with balsamic, garnish with basil."),
        ],
    },
    {
        "title": "Vegetable Frittata",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 20,
        "ingredients": [
            ("egg", Decimal("6"), "Stk"),
            ("bell pepper", Decimal("1"), "Stk"),
            ("zucchini", Decimal("1"), "Stk"),
            ("onion", Decimal("1"), "Stk"),
            ("gouda", Decimal("100"), "g"),
            ("olive oil", Decimal("2"), "EL"),
            ("salt", Decimal("1"), "TL"),
            ("black pepper", Decimal("1"), "Prise"),
        ],
        "steps": [
            ("MANUAL", "Dice vegetables, sauté in olive oil until soft."),
            ("MANUAL", "Whisk eggs with salt, pepper, and half the cheese."),
            ("MANUAL", "Pour eggs over vegetables in the pan."),
            ("MANUAL", "Top with remaining cheese."),
            ("MACHINE", "Cook on low heat 10 min, then broil 3 minutes until set."),
        ],
    },
    {
        "title": "Creamy Leek and Potato Bake",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 15,
        "cook_time_minutes": 40,
        "ingredients": [
            ("potato", Decimal("600"), "g"),
            ("leek", Decimal("2"), "Stk"),
            ("cream", Decimal("200"), "ml"),
            ("gouda", Decimal("100"), "g"),
            ("butter", Decimal("20"), "g"),
            ("salt", Decimal("1"), "TL"),
            ("black pepper", Decimal("1"), "Prise"),
        ],
        "steps": [
            ("MANUAL", "Slice potatoes and leeks thinly."),
            ("MANUAL", "Layer potatoes and leeks in a buttered dish."),
            ("MANUAL", "Season each layer, pour cream over."),
            ("MANUAL", "Top with cheese."),
            ("MACHINE", "Bake at 180°C for 40 minutes."),
        ],
    },
    {
        "title": "Sausage and Bean Stew",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 30,
        "ingredients": [
            ("sausage", Decimal("4"), "Stk"),
            ("kidney beans", Decimal("250"), "g"),
            ("canned tomatoes", Decimal("400"), "g"),
            ("onion", Decimal("1"), "Stk"),
            ("garlic", Decimal("2"), "Stk"),
            ("paprika powder", Decimal("1"), "TL"),
            ("vegetable broth", Decimal("250"), "ml"),
            ("olive oil", Decimal("1"), "EL"),
        ],
        "steps": [
            ("MANUAL", "Slice sausages, dice onion."),
            ("MANUAL", "Brown sausage in olive oil, set aside."),
            ("MANUAL", "Sauté onion and garlic, add paprika."),
            ("MANUAL", "Add beans, tomatoes, broth, and sausage. Simmer 25 min."),
        ],
    },
    {
        "title": "Broccoli Pesto Pasta",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 15,
        "ingredients": [
            ("penne", Decimal("250"), "g"),
            ("broccoli", Decimal("300"), "g"),
            ("pesto", Decimal("3"), "EL"),
            ("pine nuts", Decimal("30"), "g"),
            ("parmesan", Decimal("30"), "g"),
            ("olive oil", Decimal("1"), "EL"),
        ],
        "steps": [
            ("MACHINE", "Cook pasta and broccoli together."),
            ("MANUAL", "Toast pine nuts in a dry pan."),
            ("MANUAL", "Toss pasta and broccoli with pesto and olive oil."),
            ("MANUAL", "Top with pine nuts and parmesan."),
        ],
    },
    {
        "title": "Creamy Chicken and Spinach",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 20,
        "ingredients": [
            ("chicken breast", Decimal("2"), "Stk"),
            ("spinach", Decimal("200"), "g"),
            ("cream cheese", Decimal("100"), "g"),
            ("garlic", Decimal("2"), "Stk"),
            ("olive oil", Decimal("1"), "EL"),
            ("salt", Decimal("1"), "TL"),
            ("black pepper", Decimal("1"), "Prise"),
        ],
        "steps": [
            ("MANUAL", "Season and sear chicken until cooked through. Slice."),
            ("MANUAL", "In the same pan, sauté garlic and spinach."),
            ("MANUAL", "Add cream cheese, stir until melted into a sauce."),
            ("MANUAL", "Return chicken to pan and coat with sauce."),
        ],
    },
    {
        "title": "Mexican Rice Bowl",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 20,
        "ingredients": [
            ("rice", Decimal("200"), "g"),
            ("kidney beans", Decimal("200"), "g"),
            ("corn", Decimal("150"), "g"),
            ("avocado", Decimal("1"), "Stk"),
            ("tomato", Decimal("2"), "Stk"),
            ("cumin", Decimal("1"), "TL"),
            ("lemon", Decimal("1"), "Stk"),
            ("salt", Decimal("1"), "TL"),
        ],
        "steps": [
            ("MACHINE", "Cook rice."),
            ("MANUAL", "Warm beans and corn with cumin."),
            ("MANUAL", "Dice tomato and avocado."),
            ("MANUAL", "Assemble bowls: rice, beans, corn, tomato, avocado. Squeeze lemon."),
        ],
    },
    {
        "title": "Mushroom and Spinach Quesadilla",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 10,
        "ingredients": [
            ("tortilla wraps", Decimal("4"), "Stk"),
            ("mushroom", Decimal("200"), "g"),
            ("spinach", Decimal("100"), "g"),
            ("cheddar", Decimal("100"), "g"),
            ("garlic", Decimal("1"), "Stk"),
            ("olive oil", Decimal("1"), "EL"),
        ],
        "steps": [
            ("MANUAL", "Sauté mushrooms, garlic, and spinach in olive oil."),
            ("MANUAL", "Fill tortillas with veggies and cheese, fold in half."),
            ("MANUAL", "Cook in a dry pan until crispy and cheese melts, 2 min per side."),
        ],
    },
    {
        "title": "Cucumber Yogurt Soup",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 0,
        "ingredients": [
            ("cucumber", Decimal("2"), "Stk"),
            ("yogurt", Decimal("300"), "g"),
            ("garlic", Decimal("1"), "Stk"),
            ("lemon", Decimal("1"), "Stk"),
            ("olive oil", Decimal("2"), "EL"),
            ("salt", Decimal("1"), "TL"),
            ("fresh parsley", Decimal("1"), "EL"),
        ],
        "steps": [
            ("MANUAL", "Peel and roughly chop cucumbers."),
            ("MANUAL", "Blend cucumber, yogurt, garlic, lemon juice, and salt."),
            ("MANUAL", "Drizzle with olive oil and garnish with parsley. Serve cold."),
        ],
    },
    {
        "title": "Honey Mustard Chicken",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 25,
        "ingredients": [
            ("chicken breast", Decimal("2"), "Stk"),
            ("honey", Decimal("2"), "EL"),
            ("mustard", Decimal("2"), "EL"),
            ("garlic", Decimal("2"), "Stk"),
            ("olive oil", Decimal("1"), "EL"),
            ("potato", Decimal("400"), "g"),
            ("salt", Decimal("1"), "TL"),
        ],
        "steps": [
            ("MANUAL", "Mix honey, mustard, and minced garlic."),
            ("MANUAL", "Season chicken, coat with honey mustard glaze."),
            ("MANUAL", "Cut potatoes into wedges, toss with olive oil."),
            ("MACHINE", "Bake chicken and potatoes at 200°C for 25 minutes."),
        ],
    },
    {
        "title": "One-Pot Chili",
        "list_type": "TO_TRY",
        "default_servings": 6,
        "prep_time_minutes": 15,
        "cook_time_minutes": 40,
        "ingredients": [
            ("ground beef", Decimal("500"), "g"),
            ("kidney beans", Decimal("250"), "g"),
            ("canned tomatoes", Decimal("400"), "g"),
            ("onion", Decimal("1"), "Stk"),
            ("garlic", Decimal("3"), "Stk"),
            ("cumin", Decimal("2"), "TL"),
            ("chili flakes", Decimal("1"), "TL"),
            ("paprika powder", Decimal("1"), "TL"),
        ],
        "steps": [
            ("MANUAL", "Brown ground beef, drain fat."),
            ("MANUAL", "Sauté onion and garlic, add all spices."),
            ("MANUAL", "Add tomatoes and beans. Simmer 35 minutes."),
        ],
    },
    {
        "title": "Creamy Pumpkin Soup",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 15,
        "cook_time_minutes": 30,
        "ingredients": [
            ("sweet potato", Decimal("500"), "g"),
            ("onion", Decimal("1"), "Stk"),
            ("garlic", Decimal("2"), "Stk"),
            ("vegetable broth", Decimal("500"), "ml"),
            ("cream", Decimal("100"), "ml"),
            ("curry powder", Decimal("1"), "TL"),
            ("olive oil", Decimal("2"), "EL"),
            ("salt", Decimal("1"), "TL"),
        ],
        "steps": [
            ("MANUAL", "Peel and cube sweet potatoes."),
            ("MANUAL", "Sauté onion and garlic in olive oil."),
            ("MANUAL", "Add sweet potatoes, broth, and curry powder. Simmer 25 min."),
            ("MANUAL", "Blend until smooth, stir in cream."),
        ],
    },
    {
        "title": "Pan-Seared Salmon with Asparagus",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 5,
        "cook_time_minutes": 15,
        "ingredients": [
            ("salmon fillet", Decimal("2"), "Stk"),
            ("green beans", Decimal("300"), "g"),
            ("butter", Decimal("20"), "g"),
            ("lemon", Decimal("1"), "Stk"),
            ("garlic", Decimal("2"), "Stk"),
            ("salt", Decimal("1"), "TL"),
            ("black pepper", Decimal("1"), "Prise"),
        ],
        "steps": [
            ("MANUAL", "Season salmon with salt and pepper."),
            ("MANUAL", "Sear salmon skin-side down in butter, 4 min per side."),
            ("MANUAL", "In the same pan, sauté green beans with garlic."),
            ("MANUAL", "Squeeze lemon over everything before serving."),
        ],
    },
    {
        "title": "Loaded Sweet Potato",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 5,
        "cook_time_minutes": 45,
        "ingredients": [
            ("sweet potato", Decimal("2"), "Stk"),
            ("chickpeas", Decimal("200"), "g"),
            ("feta", Decimal("50"), "g"),
            ("spinach", Decimal("50"), "g"),
            ("olive oil", Decimal("2"), "EL"),
            ("cumin", Decimal("1"), "TL"),
            ("lemon", Decimal("1"), "Stk"),
        ],
        "steps": [
            ("MACHINE", "Bake sweet potatoes at 200°C for 45 minutes."),
            ("MANUAL", "Toss chickpeas with olive oil and cumin, warm in a pan."),
            ("MANUAL", "Split sweet potatoes, fill with chickpeas and spinach."),
            ("MANUAL", "Crumble feta on top, squeeze lemon over."),
        ],
    },
    {
        "title": "Ginger Carrot Soup",
        "list_type": "TO_TRY",
        "default_servings": 4,
        "prep_time_minutes": 10,
        "cook_time_minutes": 25,
        "ingredients": [
            ("carrot", Decimal("500"), "g"),
            ("onion", Decimal("1"), "Stk"),
            ("ginger", Decimal("2"), "TL"),
            ("vegetable broth", Decimal("500"), "ml"),
            ("coconut milk", Decimal("200"), "ml"),
            ("olive oil", Decimal("1"), "EL"),
            ("salt", Decimal("1"), "TL"),
        ],
        "steps": [
            ("MANUAL", "Peel and chop carrots, dice onion."),
            ("MANUAL", "Sauté onion and ginger in olive oil."),
            ("MANUAL", "Add carrots and broth. Simmer 20 minutes."),
            ("MANUAL", "Blend until smooth, stir in coconut milk."),
        ],
    },
    {
        "title": "Penne Arrabbiata",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 5,
        "cook_time_minutes": 20,
        "ingredients": [
            ("penne", Decimal("250"), "g"),
            ("canned tomatoes", Decimal("400"), "g"),
            ("garlic", Decimal("3"), "Stk"),
            ("chili flakes", Decimal("1"), "TL"),
            ("olive oil", Decimal("3"), "EL"),
            ("fresh parsley", Decimal("1"), "EL"),
            ("salt", Decimal("1"), "TL"),
        ],
        "steps": [
            ("MACHINE", "Cook penne until al dente."),
            ("MANUAL", "Sauté garlic and chili flakes in olive oil."),
            ("MANUAL", "Add tomatoes and salt, simmer 15 minutes."),
            ("MANUAL", "Toss with pasta and garnish with parsley."),
        ],
    },
    {
        "title": "Chicken Fried Rice",
        "list_type": "TO_TRY",
        "default_servings": 2,
        "prep_time_minutes": 10,
        "cook_time_minutes": 15,
        "ingredients": [
            ("rice", Decimal("250"), "g"),
            ("chicken breast", Decimal("200"), "g"),
            ("egg", Decimal("2"), "Stk"),
            ("carrot", Decimal("1"), "Stk"),
            ("frozen peas", Decimal("100"), "g"),
            ("soy sauce", Decimal("2"), "EL"),
            ("sesame oil", Decimal("1"), "EL"),
            ("garlic", Decimal("2"), "Stk"),
        ],
        "steps": [
            ("MACHINE", "Cook rice and let it cool."),
            ("MANUAL", "Dice chicken, sauté until golden. Set aside."),
            ("MANUAL", "Scramble eggs, set aside."),
            ("MANUAL", "Stir-fry carrot, peas, and garlic. Add rice and soy sauce."),
            ("MANUAL", "Combine with chicken and eggs, drizzle sesame oil."),
        ],
    },
]


class Command(BaseCommand):
    help = "Seed the database with sample recipes (10 known, 50 to-try)"

    def add_arguments(self, parser):
        parser.add_argument(
            "--household",
            type=str,
            help="Name of the household to add recipes to (uses first household if omitted)",
        )
        parser.add_argument(
            "--clear",
            action="store_true",
            help="Delete all existing recipes before seeding",
        )

    def handle(self, *args, **options):
        # Ensure units exist
        if not Unit.objects.exists():
            raise CommandError("No units found. Run 'python manage.py seed_units' first.")

        # Find household
        if options["household"]:
            try:
                household = Household.objects.get(name=options["household"])
            except Household.DoesNotExist as err:
                raise CommandError(f"Household '{options['household']}' not found.") from err
        else:
            first_household = Household.objects.first()
            if not first_household:
                raise CommandError("No households found. Create one first.")
            household = first_household

        if options["clear"]:
            count, _ = Recipe.objects.filter(household=household).delete()
            self.stdout.write(f"Deleted {count} existing recipe-related objects.")

        # Cache units and ingredients
        unit_map = {u.abbreviation: u for u in Unit.objects.all()}

        # Create ingredients
        ingredient_map = {}
        for ing_data in INGREDIENTS:
            obj, _ = Ingredient.objects.get_or_create(
                name_en=ing_data["name_en"],
                defaults={
                    "name_de": ing_data["name_de"],
                    "category": ing_data["category"],
                },
            )
            ingredient_map[ing_data["name_en"]] = obj

        self.stdout.write(f"Ensured {len(INGREDIENTS)} ingredients exist.")

        # Create recipes
        known_count = 0
        try_count = 0

        for recipe_data in RECIPES:
            # Skip if recipe already exists in this household
            if Recipe.objects.filter(household=household, title=recipe_data["title"]).exists():
                self.stdout.write(f"  Skipping '{recipe_data['title']}' (already exists)")
                continue

            recipe = Recipe.objects.create(
                household=household,
                title=recipe_data["title"],
                list_type=recipe_data["list_type"],
                default_servings=recipe_data["default_servings"],
                prep_time_minutes=recipe_data["prep_time_minutes"] or None,
                cook_time_minutes=recipe_data["cook_time_minutes"] or None,
            )

            # Add ingredients
            for order, (ing_name, quantity, unit_abbr) in enumerate(recipe_data["ingredients"]):
                RecipeIngredient.objects.create(
                    recipe=recipe,
                    ingredient=ingredient_map[ing_name],
                    quantity=quantity,
                    unit=unit_map[unit_abbr],
                    order=order,
                )

            # Add cooking steps
            for step_num, (method, instruction) in enumerate(recipe_data["steps"], start=1):
                CookingStep.objects.create(
                    recipe=recipe,
                    method=method,
                    step_number=step_num,
                    instruction=instruction,
                )

            if recipe_data["list_type"] == "KNOWN":
                known_count += 1
            else:
                try_count += 1

        self.stdout.write(
            self.style.SUCCESS(
                f"Seeded {known_count} known recipes and {try_count} to-try recipes "
                f"for household '{household.name}'."
            )
        )
