# Generated by Django 5.1.15 on 2026-02-24 12:20

import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Ingredient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=255)),
                ('name_en', models.CharField(max_length=255)),
                ('category', models.CharField(choices=[('PRODUCE', 'Produce'), ('DAIRY', 'Dairy'), ('MEAT', 'Meat'), ('PANTRY', 'Pantry'), ('FROZEN', 'Frozen'), ('OTHER', 'Other')], default='OTHER', max_length=10)),
            ],
            options={
                'ordering': ['name_en'],
            },
        ),
        migrations.CreateModel(
            name='Unit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_de', models.CharField(max_length=50)),
                ('name_en', models.CharField(max_length=50)),
                ('abbreviation', models.CharField(max_length=10)),
                ('conversion_factor', models.DecimalField(decimal_places=6, default=Decimal('1'), max_digits=10)),
                ('base_unit', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='derived_units', to='recipes.unit')),
            ],
        ),
    ]
