# Generated by Django 5.1.15 on 2026-02-25 00:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0002_recipe_cookingstep_recipeingredient'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='leftover_days',
            field=models.PositiveIntegerField(default=1),
        ),
    ]
