# Generated by Django 5.1.15 on 2026-02-25 00:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0003_recipe_leftover_days'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recipe',
            name='leftover_days',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
