# Generated by Django 5.1.15 on 2026-02-26 05:19

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0004_alter_recipe_leftover_days'),
        ('users', '0009_replace_json_with_real_fields'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('category', models.CharField(choices=[('DIETARY', 'Dietary'), ('PROTEIN', 'Protein'), ('CUISINE', 'Cuisine'), ('MEAL_TYPE', 'Meal Type')], max_length=20)),
                ('name_en', models.CharField(max_length=60)),
                ('name_de', models.CharField(max_length=60)),
                ('is_default', models.BooleanField(default=False)),
                ('household', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='users.household')),
            ],
            options={
                'ordering': ['category', 'name_en'],
            },
        ),
        migrations.AddField(
            model_name='recipe',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='recipes', to='recipes.tag'),
        ),
        migrations.AddConstraint(
            model_name='tag',
            constraint=models.UniqueConstraint(fields=('household', 'category', 'name_en'), name='unique_tag_per_household_category'),
        ),
    ]
