# Generated by Django 5.1.15 on 2026-02-26 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0005_tag_recipe_tags_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cookingstep',
            name='direction',
            field=models.CharField(blank=True, choices=[('LEFT', 'Left'), ('RIGHT', 'Right')], default='', max_length=5),
        ),
        migrations.AddField(
            model_name='cookingstep',
            name='duration_seconds',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookingstep',
            name='program_type',
            field=models.CharField(blank=True, choices=[('MANUAL_COOKING', 'Manual Cooking'), ('CHOPPING', 'Chopping'), ('KNEADING', 'Kneading'), ('STEAMING', 'Steaming'), ('BLENDING', 'Blending'), ('SEARING', 'Searing'), ('SLOW_COOKING', 'Slow Cooking'), ('SOUS_VIDE', 'Sous Vide'), ('WEIGHING', 'Weighing'), ('TURBO', 'Turbo'), ('EGG_COOKING', 'Egg Cooking'), ('FERMENTATION', 'Fermentation'), ('PRE_CLEANING', 'Pre-Cleaning')], default='', max_length=20),
        ),
        migrations.AddField(
            model_name='cookingstep',
            name='speed',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookingstep',
            name='temperature',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cookingstep',
            name='turbo',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='cookingstep',
            name='weight_grams',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cookingstep',
            name='instruction',
            field=models.TextField(blank=True, default=''),
        ),
    ]
