# Generated by Django 5.1.15 on 2026-02-26 21:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('recipes', '0006_cookingstep_direction_cookingstep_duration_seconds_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='recipe',
            name='description',
            field=models.TextField(blank=True, default=''),
        ),
    ]
