# Generated by Django 5.1.15 on 2026-02-24 11:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0002_household_alter_user_settings_user_active_household_and_more'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='householdmember',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='householdmember',
            name='role',
            field=models.CharField(choices=[('OWNER', 'Owner'), ('MEMBER', 'Member')], default='MEMBER', max_length=10),
        ),
        migrations.AddConstraint(
            model_name='householdmember',
            constraint=models.UniqueConstraint(fields=('household', 'user'), name='unique_household_user'),
        ),
    ]
