# Generated by Django 5.1.15 on 2026-02-24 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_invite'),
    ]

    operations = [
        migrations.AddField(
            model_name='invite',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
    ]
