# Generated by Django 5.1.15 on 2026-02-24 21:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_invite'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='apple_id',
        ),
    ]
