# Generated by Django 5.1.15 on 2026-02-25 16:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_passkeycredential'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='onboarding_step',
            field=models.CharField(choices=[('CHANGE_PASSWORD', 'Change Password'), ('ADD_PASSKEY', 'Add Passkey'), ('CREATE_HOUSEHOLD', 'Create Household'), ('COMPLETED', 'Completed')], default='CHANGE_PASSWORD', max_length=20),
        ),
    ]
