# Generated by Django 6.0.2 on 2026-02-26 04:56

import users.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_user_onboarding_step'),
    ]

    operations = [
        migrations.AddField(
            model_name='household',
            name='settings',
            field=models.JSONField(default=dict),
        ),
    ]
