# Generated by Django 6.0.2 on 2026-02-26 05:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_add_household_settings'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='household',
            name='settings',
        ),
        migrations.RemoveField(
            model_name='user',
            name='settings',
        ),
        migrations.AddField(
            model_name='household',
            name='ai_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='household',
            name='gemini_api_key',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
